sonar.projectKey=mcamip_Sistema_Votacion_Proyecto
sonar.organization=mcamip
sonar.sources=.
sonar.python.version=3.12
sonar.exclusions=tests/**, test.py, alembic/**, __pycache__/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
