"""Agregar columna descripcion a carrera

Revision ID: 5fd4a29cc43d
Revises: da39a57fe12c
Create Date: 2026-09-14 22:06:42.430606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd4a29cc43d'
down_revision: Union[str, Sequence[str], None] = 'da39a57fe12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrera', sa.Column('descripcion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carrera', 'descripcion')
    # ### end Alembic commands ###
